name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Build
        run: |
          npm install
          npx tsc
          npx webpack
          mkdir out
          touch out/.nojekyll
          cp index.html out/
          cp -r dist/ out/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: out
          clean: true
